name: Deploy to GitHub Pages

on:
  # To manually run the workflow incase it doesn't trigger.
  workflow_dispatch:
    inputs:
      forceRun:
        description: 'ForceRun - Forcefully runs the workflow regardless of whether its running in a fork or not'
        required: false
        default: false
        type: boolean
  push:
    branches:
      # change this branch name incase v5 branch is deleted/moved.
      - v5
    paths: 
      - "website/**"
      - "**.ts"
      - "README.md"
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on
permissions:
  contents: write

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    if: github.repository_owner == 'parasop' || inputs.forceRun == true
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci
        # setting the working directory as that's where the docs/website exists.
        working-directory: ./website
      - name: Build website
        run: |
          cd website
          npm run build

      # Popular action to deploy to GitHub Pages:
      # Docs: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          keep_files: true
          # Build output to publish to the `gh-pages` branch:
          publish_dir: ./website/build
          # The following lines assign commit authorship to the official
          # GH-Actions bot for deploys to `gh-pages` branch:
          # https://github.com/actions/checkout/issues/13#issuecomment-724415212
          # The GH actions bot is used by default if you didn't specify the two fields.
          # You can swap them out with your own user credentials.
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
